### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by tts** [aourednik/SPARQLchunks#1]
Having my first runs with your nice new package.

Is there a way to bypass the proxy settings? I'm not working in an office but at home, and I am on Windows 10.

```
Error in curl::ie_get_proxy_for_url(ep) : 
  ERROR_WINHTTP_UNABLE_TO_DOWNLOAD_SCRIPT
```

**Comment by aourednik** [comment]
Thanks for trying out the package. What funcion triggered the error?
There seems to be a problem with downloading the PAC script on your machine. Perhaps this thread could help: https://github.com/r-lib/httr/issues/417
Or this on stackoverflow: https://stackoverflow.com/questions/33538695/how-to-tell-r-to-use-proxy-auto-config-script-pac-in-windows

Can you try to run this (replacing endpoint and query with what you need):

```r
endpoint <- "https://lindas.admin.ch/query" 
proxy_url <- curl::ie_get_proxy_for_url(endpoint)
proxy_config <- use_proxy(url=proxy_url)
query <- "PREFIX schema: <http://schema.org/>
SELECT * WHERE {
?sub a schema:DataCatalog .
?subtype a schema:DataType .
}"
querymanual <- paste(endpoint, "?", "query", "=", gsub("\\+", "%2B", URLencode(query, reserved = TRUE)), "", sep = "")
queryres <- GET(querymanual,proxy_config,timeout(60))
queryres
```

**Comment by tts** [comment]
Thanks for the the code, and the links. 

```
endpoint <- "https://lindas.admin.ch/query" 
proxy_url <- curl::ie_get_proxy_for_url(endpoint)
```
throws the same error as I mentioned.

Anyway, this is not a big deal because I can always use your non-package chunk code, and comment out the proxy there. 

Personally, I don't need a proxy. I understand that most of the users of your package might need.

**Comment by aourednik** [comment]
If the proxy check is turned off the code runs well on your Windows machine?  

If that is the case, I'll make the proxy thing optional in the package. (There is no error on macOS, R simply ingnoresd the instruction)

**Comment by aourednik** [comment]
@tts  I've updated the package. It should no longer try to set the proxy parameters unless the user explicitetely asks for it. 
Could you test?

**Comment by tts** [comment]
Perfect, it works now! Thank you for reacting so quickly.

One more question (writing it in here although should really be separate, sorry): is it intentional that `output.var` is assigned to `knitr::knit_global()`?  As it is now,  `output.var` needs to be written to a file for further access. Probably what I'd do anyhow... 

I'm not that familiar with environments, having done no development work myself. Just curious.

**Comment by aourednik** [comment]
Thanks for testing. Happy it works. The writing to knit_global() is inspired from the sql engine included in knitr:

https://github.com/yihui/knitr/blob/master/R/engine.R

```
varname = options$output.var # line 605
# assign varname if requested
if (!is.null(varname)) assign(varname, data, envir = knit_global()) # line 699
```

This seems to be the only way to export the data frame object  from a chunk into the global environement  The objects of the globalEnv are accessible from the rest of the code and appear also in the RStudio Evironment explorer. 

Normally, writing to the global environment from a package is bad, since the created object could conflict with an object bearing an identical name defined by the user. But in this case, the user defines herself the name of the object. This is what setting a name to output.var does. When you write output.var="abcd" in the chunk header,  you say: write the result of my SPARQL query to the object "abcd". 

To then write the object to a hard drive as a file after you've executed the chunk, you can use any standard R command, for instance :

```
data.table::fwrite(abcd,"myfile.csv")
```

**Comment by tts** [comment]
Thanks again, that was a clear explanation. The reason why I asked about the environment was that I did not see the result object anywhere, the RStudio Explorer was completely empty. However, this proved to be yet another issue with the RStudio itself because when I run the code now, the object is there. Strange behavior. I guess it is time to update from Windows 10 to Windows 11 and hope that it will render these errors obsolete.
